### ISSUE TITLE
Small things

### ISSUE THREAD

**Issue by badboy** [OpenTechSchool-Dortmund/otsconf_private#4]
- [x] Carstens Text ist zu lang: `Student | OpenTechSchool Dortmund | -it’s a robot!-` (it's a robot einfach weglassen)
- [x] Avatare selbst hosten (aktuell Bilder von Twitter, geht kaputt wenn da jemand sein Bild mal ändert)
- [x] Links unter allen Bildern vervollständigen
- [x] Kontaktdaten-Tabelle im CoC wird nicht gerendert (same for legal)

**Comment by zoepage** [comment]
Avas hosten wir, wenn jeder sich für seins entschieden hat;)

**Comment by rthbrst** [comment]
- [x] Link "Legal" in "Impressum/Imprint" ändern.
- [x] Header-Foto: Hochauflösende Version anfordern + Copyright-Hinweis dran!
- [x] Favicon ist noch das von conc.at.
