### ISSUE TITLE
Textfragen Location

### ISSUE THREAD

**Issue by rthbrst** [OpenTechSchool-Dortmund/otsconf_private#5]
Im Text zur Location sind mir noch Dinge aufgefallen, die nicht stimmen. Wir sollten uns überlegen, wie wir die ändern.
- "The public space of the location has a guiding system for the blind." - Nicht dass ich wüsste. Weisen wir explizit darauf hin, dass Hilfe nötig sein könnte?
- "There is accessible parking around the venue." - Es gibt kaum Parkplätze am U und ich weiß auch nicht, inwiefern man dafür, wie an der Straße, bezahlen muss. Ich würde sagen, wir weisen daher darauf hin, dass es nur wenige Parkplätze direkt am U gibt und dass wir die Anreise per Bahn empfehlen, weil nur ein paar Schritte vom Hbf weg. Wer dringend einen Parkplatz braucht, soll sich bei uns melden.
- "The track is on the 7th floor, accessible with three elevators. No steps required." - Wollen wir trotzdem darum bitten, dass sich Gehbehinderte bei uns vorher melden, damit wir sicherstellen können, dass es keine Probleme gibt?

**Comment by badboy** [comment]
Punkt 3: Ja, auf jeden Fall anbieten sich zu melden. Wenn wir vorher von so Dingen wissen, können wir das besser handlen

**Comment by zoepage** [comment]
##### "The public space of the location has a guiding system for the blind." - Nicht dass ich wüsste. Weisen wir explizit darauf hin, dass Hilfe nötig sein könnte?

das steht so auf der Seite... ;) daher auch im "public space" und nicht überall. oben ist dann ja nicht mehr public space, aber dafür können wir ggf jemanden von den Helfern nehmen.

##### "There is accessible parking around the venue." - Es gibt kaum Parkplätze am U und ich weiß auch nicht, inwiefern man dafür, wie an der Straße, bezahlen muss. Ich würde sagen, wir weisen daher darauf hin, dass es nur wenige Parkplätze direkt am U gibt und dass wir die Anreise per Bahn empfehlen, weil nur ein paar Schritte vom Hbf weg. Wer dringend einen Parkplatz braucht, soll sich bei uns melden.

erneut... steht auf deren Seite ;)

##### "The track is on the 7th floor, accessible with three elevators. No steps required." - Wollen wir trotzdem darum bitten, dass sich Gehbehinderte bei uns vorher melden, damit wir sicherstellen können, dass es keine Probleme gibt?

das fragen wir so oder so bei der anmeldung bzw sagen, dass wenn leute "assistence" brauchen, das anmelden können(!), nicht müssen. müsste aber auch bereits dort stehen.
